language: objective-c
before_install:
  - brew update
  - brew install xctool
  - sudo easy_install cpp-coveralls
script:
  - make test
after_success:
- ./coveralls.sh -r ./ -e UICKeyChainStore -e UICKeyChainStoreTests